meta:
  name: medtune beta platform
  description: medtune beta test
  version: v0.1.4
  prod: true

database:
  type: postgres
  prod: medtune
  test: medtune-test
  creds:
    host: postgres.default.svc.cluster.local
    port: 5432
    user: mdtn
    password: mdtn
  ssl_mode: 0
  max_idle_conn: 100
  max_open_conn: 100
  
session:
  type: redis
  address: redis.default.svc.cluster.local:6379
  secret: A0123456789
  password:
  database: 0

crypto:
  algo: SHA256
  salt: MORE-SALT-PLEASE

public:
  static: ./static
  prefix: /static

secrets:
  signup:
    - supersecret
    - siistrasbourg

create:
  users:
    - username: admin
      email: admin@medtune.org
      password: admin
      account_level: 1
      account_type: admin
      account_status: true

    - username: test
      email: test@medtune.org
      password: test
      account_level: 5
      account_type: default
      account_status: true

capsul:
  inception:
    name: imagenet-inception-v3
    model: inception
    signature: predict_images
    version: 1
    address: inception.default.svc.cluster.local:10010
  
  mnist:
    name: mnist-lenet
    model: mnist
    signature: predict_images
    version: 1
    address: mnist.default.svc.cluster.local:10000

  mura-irn-v2:
    name: mura-inception-resnet-v2
    model: mura_inception_resnet_v2
    signature: predict_images
    version: 1
    address: mura-irn-v2.default.svc.cluster.local:10021

  mura-mn-v2:
    name: mura-mobilenet-v2
    model: mura
    signature: predict_images
    version: 1
    address: mura-mn-v2.default.svc.cluster.local:10020

  chexray-mn-v2:
    name: chexray-mobilenet-v2
    model: chexray
    signature: predict_images
    version: 1
    address: chexray-mn-v2.default.svc.cluster.local:10030

  chexray-dn-121:
    name: chexray-densenet-121
    model: chexray
    signature: process_img
    version: 1
    address: chexray-dn-121.default.svc.cluster.local:10031

custom_capsul:
  mura-mn-v2-cam:
    name: mura-mobilenet-v2-cam
    model: mura
    signature: run_cam
    version: 1
    address: mura-mn-v2-cam.default.svc.cluster.local:11020

  chexray-mn-v2-cam:
    name: chexray-mobilenet-v2-cam
    model: chexray
    signature: run_cam
    version: 1
    address: chexray-mn-v2-cam.default.svc.cluster.local:11030

  chexray-pp-helper:
    name: chexray-pp-helper
    model: none
    signature: process_img
    version: 1
    address: chexray-pp.default.svc.cluster.local:12030