meta:
  name: medtune beta platform
  description: beta test
  version: iron-0.1.0
  prod: true

database:
  type: postgres
  prod: medtune
  test: medtune-test
  creds:
    host: postgres #postgres
    port: 5432
    user: mdtn
    password: mdtn
  
session:
  type: cookie
  random: true
  name: default-session
  secret: A0123456789

crypto:
  algo: SHA256
  salt: MORE-SALT-PLEASE

public:
  static: ./static

capsules:
  engine: docker
  items:
    - image: medtune/inception-0.0.0
      mapped-demo: inception-imagenet
      port: 8080

    - image: medtune/mnist-0.0.0
      mapped-demo: mnist
      port: 9090

    - image: medtune/chexray-0.0.0

    - image: medtune/mnist-0.0.0
    
    - image: medtune/mura-0.0.0

secrets:
  signup:
    - supersecret
    - siistrasbourg

create:
  users:
    - username: admin
      email: admin@medtune.org
      password: admin

    - username: test
      email: test@medtune.org
      password: test
