meta:
  name: medtune beta platform
  description: medtune beta test
  version: v0.1.1
  prod: true

database:
  type: postgres
  prod: medtune
  test: medtune-test
  creds:
    host: postgres
    port: 5432
    user: mdtn
    password: mdtn
  
session:
  type: cookie
  random: true
  name: default-session
  secret: A0123456789

crypto:
  algo: SHA256
  salt: MORE-SALT-PLEASE

public:
  static: ./static

capsul:
  inception:
    model: inception
    signature: predict_images
    version: 1
    address: localhost:9001
  
  mnist:
    model: mnist
    signature: predict_images
    version: 1
    address: localhost:9000

  mura:
    model: mura
    signature: predict_images
    version: 1
    address: localhost:6666

  chexray:
    model: chexray
    signature: predict_images
    version: 1
    address: localhost:6666

secrets:
  signup:
    - supersecret
    - siistrasbourg

create:
  users:
    - username: admin
      email: admin@medtune.org
      password: admin

    - username: test
      email: test@medtune.org
      password: test
