version: '3.2'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=mdtn
      - POSTGRES_PASSWORD=mdtn
      - POSTGRES_DB=medtune
    

  redis:
    image: redis:latest
    command: --appendonly yes
    

  platform-app:
    image: medtune/beta-platform:prod
    ports:
      - 8006:8005

    depends_on:
      - postgres
      - redis
      - mnist
      - mura-mn-v2
      - mura-mn-v2-cam
      - mura-irn-v2
      - chexray-pp
      - chexray-dn-121

    links:
      - redis:redis
      - postgres:postgres
      - mnist:mnist
      - inception:inception
      - mura-mn-v2:mura-mn-v2
      - mura-irn-v2:mura-irn-v2
      - mura-mn-v2-cam:mura-cam-v2-cam
      - chexray-pp:chexray-pp
      - chexray-dn-121:chexray-dn-121

    volumes:
      - mura-images:/go/src/github.com/medtune/beta-platform/static/demos/mura/images
      - chexray-images:/go/src/github.com/medtune/beta-platform/static/demos/chexray/images

  mnist:
    image: medtune/capsul:mnist
    
  inception:
    image: medtune/capsul:inception    

  mura-mn-v2:
    image: medtune/capsul:mura-mn-v2    

  mura-irn-v2:
    image: medtune/capsul:mura-irn-v2
    
  mura-mn-v2-cam:
    image: medtune/capsul:mura-mn-v2-cam
    volumes:
      - mura-images:/medtune/data

  chexray-dn-121:
    image: medtune/capsul:chexray-dn-121
    
  chexray-pp:
    image: medtune/capsul:chexray-pp-helper
    volumes:
      - chexray-images:/medtune/data

volumes:
  mura-images: {}
  chexray-images: {}