version: 2
jobs:
  #go-latest
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: build base/build/prod images
          command: make build-all

      - run:
          name: test
          command: make tests

      - run:
          name: test
          command: make test-cov

      - run:
          name: login to docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
          
      - run:
          name: push image to registry
          command: |
            docker push medtune/beta-platform:v0.1.2
            docker push medtune/beta-platform:latest

workflows:
  version: 2
  build:
    jobs:
      - build
