version: 2
jobs:
  #go-latest
  build-base:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true
      - run:
          name: build base image
          command: make build-base

  test:
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true
      - run:
          name: test packages
          command: make tests

  test-cov:
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true
      - run:
          name: code coverage tests
          command: make test-cov

      - run:
          name: test coverage
          command: docker build -t test-cov -f Dockerfile.test-cov --build-arg CODECOV_TOKEN=$CODECOV_TOKEN .

  build-prod:
    steps:
      - checkout
      - setup_remote_docker: 
         docker_layer_caching: true
      - run:
          name: build capsul image
          command: make build-prod
      - run:
          name: login docker engine
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: push image to registry
          command: docker push medtune/beta-platform:go-1.10-linux-v0.1.2

workflows:
  version: 2
  build:
    jobs:
      - build-base
      - test:
          requires:
            - build-base
      - test-cov:
          requires:
            - build-base
      - build-prod:
          requires:
            - build-base
            - test
            - test-cov
