apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.replicas.yml -o deploy/kubernetes
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: inception
  name: inception
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: inception
    spec:
      containers:
      - image: medtune/capsul:inception
        name: inception
        ports:
        - containerPort: 10010
        resources: {}
      restartPolicy: Always
status: {}
