apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: beta-platform
    spec:
      containers:
      - name: beta-platform-v0.1.0
        image: medtune/beta-platform:v0.1.0
        ports:
        - containerPort: 8005
---
kind: Service
apiVersion: v1
metadata:
  name: mdtn-service
spec:
  selector:
    app: beta-platform
  ports:
    - protocol: TCP
      port: 8005
  type: LoadBalancer