apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.k8s.yml -o deploy/kubernetes
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mnist
  name: mnist
spec:
  replicas: 2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mnist
    spec:
      containers:
      - image: medtune/capsul:mnist
        name: mnist
        ports:
        - containerPort: 10000
        resources: {}
      restartPolicy: Always
status: {}
