apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.replicas.yml -o deploy/kubernetes
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: mura-mn-v2
  name: mura-mn-v2
spec:
  ports:
  - name: "10020"
    port: 10020
    targetPort: 10020
  selector:
    io.kompose.service: mura-mn-v2
status:
  loadBalancer: {}
