apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.replicas.yml -o deploy/kubernetes
    kompose.service.type: LoadBalancer
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: platform-app
  name: platform-app
spec:
  replicas: 10
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: platform-app
    spec:
      containers:
      - image: medtune/beta-platform:k8s
        name: platform-app
        ports:
        - containerPort: 8005
        resources: {}
        volumeMounts:
        - mountPath: /go/src/github.com/medtune/beta-platform/static/demos/mura/images
          name: mura-images
        - mountPath: /go/src/github.com/medtune/beta-platform/static/demos/chexray/images
          name: chexray-images
      restartPolicy: Always
      volumes:
      - name: mura-images
        persistentVolumeClaim:
          claimName: mura-images
      - name: chexray-images
        persistentVolumeClaim:
          claimName: chexray-images
status: {}
