apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.replicas.yml -o deploy/kubernetes
    kompose.service.type: LoadBalancer
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: platform-app
  name: platform-app
spec:
  ports:
  - name: "8005"
    port: 8005
    targetPort: 8005
  selector:
    io.kompose.service: platform-app
  type: LoadBalancer
status:
  loadBalancer: {}
